
# Nom de l'application
spring.application.name=ingredient

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/product_management_db
spring.datasource.username=ingredient_manager_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Exécuter automatiquement schema.sql et data.sql
#spring.sql.init.mode=always

# (Optionnel) afficher les requêtes SQL
logging.level.org.springframework.jdbc.core=DEBUG